server:
  port: 19450
  servlet:
    context-path: /system
    application-display-name: system

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.235.125:53336/user_system_db?useSSL=false
    username: app
    password: 6y7u8I9O
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath:mybatis/*.xml


# 图片上传地址配置
case:
  uploadPath: /data/webuser01/grad-project/upload/
  resources:
    pathPatterns: /upload/**
    resourceLocations: file:${case.uploadPath}

