server:
  port: 8080
  servlet:
    context-path: /system
    application-display-name: system

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/*.xml


# 图片上传地址配置
case:
  uploadPath: E:\data\UserSystem\target\classes\upload\
  resources:
    pathPatterns: /upload/**
    resourceLocations: file:${case.uploadPath}

